language: node_js
node_js: 
  - stable  

sudo: false

cache:
  directories:
    node_modules

install:
  - npm install -g codecov

after_script:
  - npm run cov
  - codecov

script:
  - npm run lint
  - npm run test